apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-minimal
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluentd:v1.16-1
