# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: demo-app
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@postgres-postgresql.postgresx.svc.cluster.local:5432/postgres
  # cat /etc/resolv.conf in Postgres pod to get the cluster DNS suffix
